site_name: ENIGMA infra
theme:
  name: material

features:
  - navigation.indexes
nav:
  - Welcome: index.md
  - Blog:
    - blog/index.md
  - Team:
    - team/people.md 
  - ENIGMA-PD:
    - wg/e_pd.md
  - ENIGMA-Tremor:
    - wg/e_tremor.md
  - Reviews:
    - reviews/testimonials.md
  - Partners:
    - partners/LoS.md
  - Resources:
    - resources/open_science_toolstack.md

plugins:
  - search
  - blog

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
