site_name: ENIGMA infra
theme:
  name: material

features:
  - navigation.indexes
nav:
  - Welcome: index.md
  - Blog:
    - blog/index.md
  - Team:
    - team/people.md 
  - Working Groups:
    - ENIGMA-PD:
      - Core team: wg/pd_core_team.md
      - Sites: wg/pd_sites.md
      - Projects:
        - FreeSurfer 7: wg/pd_freesurfer7.md
        - White matter lesions: wg/pd_wml.md
        - Imaging-Genetics: wg/pd_imaging_genetics.md
    - ENIGMA-Tremor:
      - Core team: wg/tremor_core_team.md
      - Sites: wg/tremor_sites.md
      - Projects:
        - FreeSurfer 7: wg/tremor_freesurfer7.md
  - Reviews:
    - reviews/testimonials.md
  - Partners:
    - partners/LoS.md
  - Resources:
    - resources/open_science_toolstack.md

plugins:
  - search
  - blog

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
