site_name: ENIGMA infra
repo_url: https://github.com/ENIGMA-infra/enigma-infra.github.io
theme:
  name: material
  logo: "logos/enigma_300DPI_small.png"
  favicon: "logos/enigma_300DPI_small.png"

features:
  - navigation.indexes
nav:
  - Welcome: index.md
  - Team:
    - team/people.md 
  - Working Groups:
    - Sites: wg/sites.md
  - Reviews:
    - reviews/testimonials.md
  - Partners:
    - partners/LoS.md
  - Resources:
    - Open Science Toolstack: resources/open_science_tools/open_science_toolstack.md
    - Setting up Nipoppy: resources/how_to_guides/setting_up_nipoppy.md
    - Processing: 
      - FreeSurfer 7: resources/how_to_guides/freesurfer7.md
      - FreeSurfer subsegmentations: resources/how_to_guides/freesurfer_subseg.md
      - FreeSurfer Quality Control toolbox: resources/how_to_guides/fsqc.md
    - Quality Assessment: resources/how_to_guides/qa.md

plugins:
  - search
  - blog

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
